### ISSUE TITLE
Server deployment - proxy - label:documentation

### ISSUE THREAD

**Issue by xploz1on** [CanastaWiki/Canasta-DockerCompose#22]
Hi there,
I been testing locally the stack and so far so good.
Wondering how would i go into deploy this in a server that has nginx-proxy-manager running (docker)
I can deploy into a fresh server with domain and all. Just wondering what would be the course of action to deploy it on a fresh server for example. I noticed it forces HTTPS. Why not include certbot in the stack?

Also trying to look up QuickStatements implementation. Maybe i missed it on the documentation? Thanks!

Best Regards,
Daniel Preugschat

**Comment by amalpaul54111** [comment]
Regarding including the certbot, as we use caddy and automatic-https is turned on. It automatically gets TLS certificates for the domain.
Ref: https://caddyserver.com/docs/automatic-https

**Comment by jeffw16** [comment]
Amal is correct about Caddy ^

Canasta for Docker Compose doesn't have QuickStatements included yet. Once we add full Wikibase support we can consider adding it.

**Comment by jeffw16** [comment]
Regarding nginx-proxy-manager: I'm not sure; we don't provide support for that here. Sorry 🤷‍♂️

**Comment by xploz1on** [comment]
Thanks for the answers.
SO if i deploy the stack on a fresh server by just imputing the domain in the .env file it will generate the SSL and work with the domain as is? 
I am not really familiar with caddy. Thanks!

**Comment by amalpaul54111** [comment]
Yeah, it should.

**Comment by xploz1on** [comment]
> Yeah, it should.

Yeah, i should have tried before asking haha. Beautifull!
I might have some questions for federated, quickstatements, etc. Hopefully i can figure it out. Thank you all!

**Comment by yaronkoren** [comment]
@xploz1on - by the way, I never want to dissuade anyone from running Canasta, but if you want to run Wikibase, you'd be much better off running the Wikibase Docker image than Canasta, I think.

**Comment by xploz1on** [comment]
> @xploz1on - by the way, I never want to dissuade anyone from running Canasta, but if you want to run Wikibase, you'd be much better off running the Wikibase Docker image than Canasta, I think.

I see. I wanted this stack to work with Wikibase. If not possible i guess ill have to use Wikibase docker. Thanks all!

**Comment by J43fura** [comment]
Is there an update on how to integrate Wikibase into canasta? :eyes:
