### ISSUE TITLE
Error in wiki installation wizard > Connect to database

### ISSUE THREAD

**Issue by qomhmd** [CanastaWiki/Canasta-DockerCompose#25]
> Cannot access the database: :real_connect(): (HY000/2002): No such file or directory.
> Check the host, username and password and try again. If using "localhost" as the database host, try using "127.0.0.1" instead (or vice versa).

**Comment by jeffw16** [comment]
What database host are you using? Is the MySQL container running?

**Comment by qomhmd** [comment]
I'm using the included MySQL container included in the package and yes, it was running. I managed to run it by entering the name of MySQL container as the database host.
