### ISSUE TITLE
Upgrade Elasticsearch to 7.10.2

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta-DockerCompose#27]
CirrusSearch for 1.39 now requires ES 7.10.2

**Comment by gitmapd** [comment]
@jeffw16 i wonder if for these cases when there's a need for upgrading certain packages, why not using watchtower or shepherd for when a docker compose is deployed it gets the updated image?

**Comment by gitmapd** [comment]
> @gitmapd There was a pull request to do this on the Canasta image authored by @vedmaka but it was abandoned.
> 
> Anyway, for this change, it would have required a manual update anyway since it is going from 6.x to 7.x. Plus, CirrusSearch is highly sensitive to which version it requires to run. For the CirrusSearch version for MediaWiki 1.39.0, only 7.10.2 is currently supported, according to the documentation on MW.o. But 7.11.x exists...

Yes, i see its always to be careful not to kill a system. Thank you.
