### ISSUE TITLE
Apache

### ISSUE THREAD

**Issue by gitmapd** [CanastaWiki/Canasta-DockerCompose#30]
Also i don't know if you guys think its a good idea...but i like apache to be reloaded when a file changes without restarting the container. So I will share a gist here:
https://gist.github.com/gitmapd/54052b3cbe0c7b8489541c83b335d814

**Comment by jeffw16** [comment]
When would a file change?

**Comment by gitmapd** [comment]
I may be approaching wrong about containers but usually you need to change configuration files for various situations and i believe that we can automate so  we don't need to restart the daemon ourselves.

**Comment by gitmapd** [comment]
> The Apache configuration files currently can't even be changed from the Docker Compose stack, meaning any changes made to it would have to be done directly to the container. Such changes are ephemeral (and are only valid for as long as the container is alive) and therefore unsupported.
> 
> I'm not sure what changes need to be made to the Apache configuration file, because up until this point, the current configuration has been designed to work well for everyone's use case, but if there are significant and legitimate use cases that require this, then we can discuss moving it from the image to this stack repo.

Yes, i know. Maybe im thinking from the perspective of a tinkerer/tinker ?

**Comment by jeffw16** [comment]
Unfortunately that use case is not supported because we do not have a legitimate use case for production for that right now. Moving confjg files from the image to the stack repo represents a technical burden. If tinkering needs to be done, I would recommend creating a derivative Dockerfile to make said changes.
