### ISSUE TITLE
Docker Compose is installed but not installed

### ISSUE THREAD

**Issue by JOd121** [CanastaWiki/Canasta-DockerCompose#35]
To whom it may concern,

Docker is installed:
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:43:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:43:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

And Docker Compose as well:
Docker Compose version v2.15.1

But running 
curl -fsL https://raw.githubusercontent.com/CanastaWiki/Canasta-CLI/main/install.sh | bash

leads to the following result:
Downloading Canasta CLI latest release
canasta             100%[===================>]   4,60M  10,7MB/s    in 0,4s    
Installing Canasta CLI
Docker is already installed.
**Docker Compose is not installed**; please follow the guide at https://docs.docker.com/compose/install/ to install it.
Please make sure you have a working kubectl if you wish to use Kubernetes as an orchestrator.

Usage: sudo canasta [COMMAND] [ARGUMENTS...]

What can I do?

Thanks in advance for any answer.

**Comment by bryandamon** [comment]
This might be related to [this issue](https://github.com/CanastaWiki/Canasta-CLI/issues/59), if so try running `sudo apt install docker-compose` to **install docker-compose** vs. **docker-compose-plugin**.

**Comment by JOd121** [comment]
Hi, bryandamon,

thank you for the hint.

If docker-compose is installed:

containerd.io will be replaced by containerd.

docker-ce, docker-ce-cli and docker-ce-rootless-extra will be removed.

docker.io and some python3 scripts will be install.

To me this seems to be a bigger change than just replacing the docker-compose-plugin by docker-compose.

What ever, it has worked for you. I will give it a try.

**Comment by yaronkoren** [comment]
It does seem like the install.sh script should be modified to handle both kinds of installations...

**Comment by JOd121** [comment]
Hi together,

@bryandamon
I followed your advice and got Canasta installed. Thanks!

@yaronkoren
That would be helpful as far as I am concerned.

**Comment by freephile** [comment]
related to https://github.com/CanastaWiki/Canasta-CLI/issues/59

**Comment by freephile** [comment]
Fixed in updated install.sh
