### ISSUE TITLE
Add a volumed-in Docker Compose override file

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta-DockerCompose#43]
Apologies if I'm not quite describing this correctly, but: it would be good for Canasta to provide a docker-compose.override.yml file which is a volume, i.e. actually stored in the host OS, so that the administrator can add their own directives.

**Comment by PiyushRaj927** [comment]
I'm sorry if I'm not understanding correctly, the current [`docker-compose.override.yml`](https://github.com/CanastaWiki/Canasta-DockerCompose/blob/main/docker-compose.override.yml) file can be used to provide additional directives and compose files lives in the host OS.
I don't understand how a volumed in override file can be beneficial or used. Can you please explain or provide examples? Thank you.

**Comment by yaronkoren** [comment]
Yes, indeed! Somehow I had completely missed the existence of this file. Sorry, and thanks for pointing that out.
